name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Build the Docker image
      # run: docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)


# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Log in to GitHub Container Registry
#       uses: docker/login-action@v1
#       with:
#         registry: ghcr.io
#         username: ${{ github.repository_owner }}
#         password: ${{ secrets.GHCR_TOKEN }}

#     - name: Build and push Scantools Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./docker/Dockerfile
#         push: true
#         tags: ghcr.io/microsoft/lamar-benchmark/scantools:latest
#         target: scantools

#     - name: Build and push Lamar Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         file: ./docker/Dockerfile
#         push: true
#         tags: ghcr.io/microsoft/lamar-benchmark/lamar:latest
#         target: lamar
