name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Scantools Docker image'
        run: |
          docker build . --tag ghcr.io/pablospe/lamar-benchmark/scantools:latest --target scantools
          docker push ghcr.io/pablospe/lamar-benchmark/scantools:latest
          docker build . --tag ghcr.io/pablospe/lamar-benchmark/scantools:$(date +%Y-%m-%d) --target scantools
          docker push ghcr.io/pablospe/lamar-benchmark/scantools:$(date +%Y-%m-%d)

      - name: Build and push Lamar Docker image
        run: |
          docker build . --tag ghcr.io/pablospe/lamar-benchmark/lamar:latest --target lamar
          docker push ghcr.io/pablospe/lamar-benchmark/lamar:latest
